# Generated by Django 5.1.4 on 2025-01-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='perex',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
