# Generated by Django 5.1 on 2025-02-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_category_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='content.category'),
        ),
        migrations.RunSQL(
            """
            INSERT INTO content_article_categories (article_id, category_id)
            SELECT id, category_id FROM content_article
            """
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
